package crypto

import "testing"

// ncsoftVectors are 15 (input, expected) pairs generated by the canonical C#
// reference implementation via gen_test_vectors.ps1. This is the authoritative
// byte-level parity check: if any one of these fails, the Go port has drifted
// from AionNetGate and AionCore will refuse logins.
//
// Regenerate by running:
//   powershell -ExecutionPolicy Bypass -File gen_test_vectors.ps1
var ncsoftVectors = []struct {
	input    string
	expected string
}{
	{"", "0x35A28484C552747441D8FEFE33A98F8F"},
	{"a", "0x353250511087A1A1940D2B2BE67C5A5A"},
	{"admin", "0x35F239833EBA3637029BBDBD70EACCCC"},
	{"test", "0xB53B56EDAC3B1D1D28B197975AC0E6E6"},
	{"password", "0xB5394575C8F9ED7144DDFBFB36AC8A8A"},
	{"123456", "0xB53AA2DEE7078F3F0A93B5B578E2C4C4"},
	{"aion", "0x3542CA7B3AAD8B8BBE270101CC567070"},
	{"1", "0xB55A9F9FDE496F6F5AC3E5E528B29494"},
	{"abcdefgh", "0x35F2BE17AE1D97F4C1587E7EB3290F0F"},
	{"ABC123", "0x35C256605D78C46257CEE8E825BF9999"},
	{"9876543210", "0x45C6B5DFE60AEAB21BBA57CB069CBABA"},
	{"shiguangAI", "0x3171FF78C14AF155DCACDA34F9634545"},
	{"LongerPassw", "0xA507CF912893D3D15CAF08915CC6E0E0"},
	{"Max16Characters1", "0x255839CFF2BBA2227B70D14FF4CD7611"},
	{"p@ssw0rd!", "0xB57BB713AE03165910E47575B8220404"},
}

// TestNCSoftHash_ReferenceParity asserts byte-level parity with the C# reference.
func TestNCSoftHash_ReferenceParity(t *testing.T) {
	for _, v := range ncsoftVectors {
		got := NCSoftHash(v.input)
		if got != v.expected {
			t.Errorf("NCSoftHash(%q) = %s, want %s", v.input, got, v.expected)
		}
	}
}

// TestNCSoftHash_Determinism asserts the same input always produces the same hash.
func TestNCSoftHash_Determinism(t *testing.T) {
	for _, v := range ncsoftVectors {
		first := NCSoftHash(v.input)
		second := NCSoftHash(v.input)
		if first != second {
			t.Errorf("non-deterministic hash for %q: %s vs %s", v.input, first, second)
		}
	}
}

// TestNCSoftHash_OutputFormat asserts the output is always "0x" + 32 hex chars.
func TestNCSoftHash_OutputFormat(t *testing.T) {
	for _, v := range ncsoftVectors {
		got := NCSoftHash(v.input)
		if len(got) != 34 {
			t.Errorf("unexpected length for %q: got %d, want 34", v.input, len(got))
		}
		if got[:2] != "0x" {
			t.Errorf("missing 0x prefix for %q: %s", v.input, got)
		}
		for i := 2; i < len(got); i++ {
			c := got[i]
			isHex := (c >= '0' && c <= '9') || (c >= 'A' && c <= 'F')
			if !isHex {
				t.Errorf("non-hex character at position %d for %q: %s", i, v.input, got)
				break
			}
		}
	}
}

// TestNCSoftHash_Truncation asserts inputs > 16 chars are truncated (not
// crashing) and produce the same hash as the 16-char prefix.
func TestNCSoftHash_Truncation(t *testing.T) {
	short := "Max16Characters1"
	long := short + "EXTRA_SUFFIX_IGNORED"
	if NCSoftHash(short) != NCSoftHash(long) {
		t.Errorf("long input not truncated at 16 chars: short=%s long=%s",
			NCSoftHash(short), NCSoftHash(long))
	}
}

func BenchmarkNCSoftHash(b *testing.B) {
	for i := 0; i < b.N; i++ {
		NCSoftHash("password")
	}
}
