// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelPatch() {
  return window['go']['main']['App']['CancelPatch']();
}

export function ChangePassword(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ChangePassword'](arg1, arg2, arg3, arg4);
}

export function ClearServerCode() {
  return window['go']['main']['App']['ClearServerCode']();
}

export function FetchLauncherConfig() {
  return window['go']['main']['App']['FetchLauncherConfig']();
}

export function GetBrand() {
  return window['go']['main']['App']['GetBrand']();
}

export function GetControlURL() {
  return window['go']['main']['App']['GetControlURL']();
}

export function GetPrefs() {
  return window['go']['main']['App']['GetPrefs']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function LaunchGame(arg1) {
  return window['go']['main']['App']['LaunchGame'](arg1);
}

export function Login(arg1, arg2, arg3) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function Register(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3, arg4);
}

export function ResetPassword(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResetPassword'](arg1, arg2, arg3);
}

export function SetClientPath(arg1, arg2) {
  return window['go']['main']['App']['SetClientPath'](arg1, arg2);
}

export function SetControlURL(arg1) {
  return window['go']['main']['App']['SetControlURL'](arg1);
}

export function SetServerCode(arg1) {
  return window['go']['main']['App']['SetServerCode'](arg1);
}

export function StartPatch(arg1) {
  return window['go']['main']['App']['StartPatch'](arg1);
}
