// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {control} from '../models';
import {main} from '../models';

export function CancelPatch():Promise<void>;

export function ChangePassword(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ClearServerCode():Promise<void>;

export function FetchLauncherConfig():Promise<control.LauncherConfig>;

export function GetBrand():Promise<main.BrandConfig>;

export function GetControlURL():Promise<string>;

export function GetPrefs():Promise<main.Prefs>;

export function LaunchGame(arg1:string):Promise<number>;

export function Login(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Logout():Promise<void>;

export function Register(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ResetPassword(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SetClientPath(arg1:string,arg2:string):Promise<void>;

export function SetControlURL(arg1:string):Promise<void>;

export function SetServerCode(arg1:string):Promise<main.BrandConfig>;

export function StartPatch(arg1:string):Promise<void>;
