// Hub-Spoke gRPC protocol for ShiguangCloud.
//
// The Gate Agent (spoke) connects to Hub (cloud) via a long-lived bidirectional
// gRPC stream. This stream carries:
//   Agent → Hub: heartbeat, metrics, events (player login/logout)
//   Hub → Agent: ban/unban, kick, config hot-push, announcements
//
// Game traffic (TCP packets) NEVER flows through this channel — only the
// control plane does. This is the foundational design principle.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/hub.proto

package hubpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentReport struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	AgentToken string                 `protobuf:"bytes,1,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentReport_Heartbeat
	//	*AgentReport_Metrics
	//	*AgentReport_Event
	Payload       isAgentReport_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentReport) Reset() {
	*x = AgentReport{}
	mi := &file_proto_hub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentReport) ProtoMessage() {}

func (x *AgentReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentReport.ProtoReflect.Descriptor instead.
func (*AgentReport) Descriptor() ([]byte, []int) {
	return file_proto_hub_proto_rawDescGZIP(), []int{0}
}

func (x *AgentReport) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

func (x *AgentReport) GetPayload() isAgentReport_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentReport) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentReport_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentReport) GetMetrics() *MetricsBatch {
	if x != nil {
		if x, ok := x.Payload.(*AgentReport_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *AgentReport) GetEvent() *PlayerEvent {
	if x != nil {
		if x, ok := x.Payload.(*AgentReport_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isAgentReport_Payload interface {
	isAgentReport_Payload()
}

type AgentReport_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentReport_Metrics struct {
	Metrics *MetricsBatch `protobuf:"bytes,3,opt,name=metrics,proto3,oneof"`
}

type AgentReport_Event struct {
	Event *PlayerEvent `protobuf:"bytes,4,opt,name=event,proto3,oneof"`
}

func (*AgentReport_Heartbeat) isAgentReport_Payload() {}

func (*AgentReport_Metrics) isAgentReport_Payload() {}

func (*AgentReport_Event) isAgentReport_Payload() {}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	PublicIp      string                 `protobuf:"bytes,2,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "online" | "degraded"
	Uptime        string                 `protobuf:"bytes,5,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Routes        []*RouteSnapshot       `protobuf:"bytes,6,rep,name=routes,proto3" json:"routes,omitempty"`
	BanCount      int32                  `protobuf:"varint,7,opt,name=ban_count,json=banCount,proto3" json:"ban_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_hub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_hub_proto_rawDescGZIP(), []int{1}
}

func (x *Heartbeat) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Heartbeat) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

func (x *Heartbeat) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Heartbeat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Heartbeat) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *Heartbeat) GetRoutes() []*RouteSnapshot {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *Heartbeat) GetBanCount() int32 {
	if x != nil {
		return x.BanCount
	}
	return 0
}

type RouteSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Active        int64                  `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	Accepted      uint64                 `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Rejected      uint64                 `protobuf:"varint,4,opt,name=rejected,proto3" json:"rejected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteSnapshot) Reset() {
	*x = RouteSnapshot{}
	mi := &file_proto_hub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteSnapshot) ProtoMessage() {}

func (x *RouteSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteSnapshot.ProtoReflect.Descriptor instead.
func (*RouteSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_hub_proto_rawDescGZIP(), []int{2}
}

func (x *RouteSnapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RouteSnapshot) GetActive() int64 {
	if x != nil {
		return x.Active
	}
	return 0
}

func (x *RouteSnapshot) GetAccepted() uint64 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *RouteSnapshot) GetRejected() uint64 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

type MetricsBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*MetricPoint         `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsBatch) Reset() {
	*x = MetricsBatch{}
	mi := &file_proto_hub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsBatch) ProtoMessage() {}

func (x *MetricsBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsBatch.ProtoReflect.Descriptor instead.
func (*MetricsBatch) Descriptor() ([]byte, []int) {
	return file_proto_hub_proto_rawDescGZIP(), []int{3}
}

func (x *MetricsBatch) GetPoints() []*MetricPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type MetricPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // "online_count", "login", "register"
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	Server        string                 `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"` // "5.8" or "4.8"
	TimestampMs   int64                  `protobuf:"varint,4,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricPoint) Reset() {
	*x = MetricPoint{}
	mi := &file_proto_hub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricPoint) ProtoMessage() {}

func (x *MetricPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricPoint.ProtoReflect.Descriptor instead.
func (*MetricPoint) Descriptor() ([]byte, []int) {
	return file_proto_hub_proto_rawDescGZIP(), []int{4}
}

func (x *MetricPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricPoint) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricPoint) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *MetricPoint) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type PlayerEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "login" | "logout" | "register"
	Account       string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Server        string                 `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"`
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,5,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerEvent) Reset() {
	*x = PlayerEvent{}
	mi := &file_proto_hub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerEvent) ProtoMessage() {}

func (x *PlayerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerEvent.ProtoReflect.Descriptor instead.
func (*PlayerEvent) Descriptor() ([]byte, []int) {
	return file_proto_hub_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PlayerEvent) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *PlayerEvent) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *PlayerEvent) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *PlayerEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type HubCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*HubCommand_BanIp
	//	*HubCommand_UnbanIp
	//	*HubCommand_KickPlayer
	//	*HubCommand_ConfigUpdate
	//	*HubCommand_Announcement
	Command       isHubCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubCommand) Reset() {
	*x = HubCommand{}
	mi := &file_proto_hub_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubCommand) ProtoMessage() {}

func (x *HubCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubCommand.ProtoReflect.Descriptor instead.
func (*HubCommand) Descriptor() ([]byte, []int) {
	return file_proto_hub_proto_rawDescGZIP(), []int{6}
}

func (x *HubCommand) GetCommand() isHubCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *HubCommand) GetBanIp() *BanIP {
	if x != nil {
		if x, ok := x.Command.(*HubCommand_BanIp); ok {
			return x.BanIp
		}
	}
	return nil
}

func (x *HubCommand) GetUnbanIp() *UnbanIP {
	if x != nil {
		if x, ok := x.Command.(*HubCommand_UnbanIp); ok {
			return x.UnbanIp
		}
	}
	return nil
}

func (x *HubCommand) GetKickPlayer() *KickPlayer {
	if x != nil {
		if x, ok := x.Command.(*HubCommand_KickPlayer); ok {
			return x.KickPlayer
		}
	}
	return nil
}

func (x *HubCommand) GetConfigUpdate() *ConfigUpdate {
	if x != nil {
		if x, ok := x.Command.(*HubCommand_ConfigUpdate); ok {
			return x.ConfigUpdate
		}
	}
	return nil
}

func (x *HubCommand) GetAnnouncement() *Announcement {
	if x != nil {
		if x, ok := x.Command.(*HubCommand_Announcement); ok {
			return x.Announcement
		}
	}
	return nil
}

type isHubCommand_Command interface {
	isHubCommand_Command()
}

type HubCommand_BanIp struct {
	BanIp *BanIP `protobuf:"bytes,1,opt,name=ban_ip,json=banIp,proto3,oneof"`
}

type HubCommand_UnbanIp struct {
	UnbanIp *UnbanIP `protobuf:"bytes,2,opt,name=unban_ip,json=unbanIp,proto3,oneof"`
}

type HubCommand_KickPlayer struct {
	KickPlayer *KickPlayer `protobuf:"bytes,3,opt,name=kick_player,json=kickPlayer,proto3,oneof"`
}

type HubCommand_ConfigUpdate struct {
	ConfigUpdate *ConfigUpdate `protobuf:"bytes,4,opt,name=config_update,json=configUpdate,proto3,oneof"`
}

type HubCommand_Announcement struct {
	Announcement *Announcement `protobuf:"bytes,5,opt,name=announcement,proto3,oneof"`
}

func (*HubCommand_BanIp) isHubCommand_Command() {}

func (*HubCommand_UnbanIp) isHubCommand_Command() {}

func (*HubCommand_KickPlayer) isHubCommand_Command() {}

func (*HubCommand_ConfigUpdate) isHubCommand_Command() {}

func (*HubCommand_Announcement) isHubCommand_Command() {}

type BanIP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	DurationMs    int64                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"` // 0 = permanent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanIP) Reset() {
	*x = BanIP{}
	mi := &file_proto_hub_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanIP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanIP) ProtoMessage() {}

func (x *BanIP) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanIP.ProtoReflect.Descriptor instead.
func (*BanIP) Descriptor() ([]byte, []int) {
	return file_proto_hub_proto_rawDescGZIP(), []int{7}
}

func (x *BanIP) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *BanIP) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BanIP) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type UnbanIP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbanIP) Reset() {
	*x = UnbanIP{}
	mi := &file_proto_hub_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbanIP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanIP) ProtoMessage() {}

func (x *UnbanIP) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanIP.ProtoReflect.Descriptor instead.
func (*UnbanIP) Descriptor() ([]byte, []int) {
	return file_proto_hub_proto_rawDescGZIP(), []int{8}
}

func (x *UnbanIP) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type KickPlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickPlayer) Reset() {
	*x = KickPlayer{}
	mi := &file_proto_hub_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickPlayer) ProtoMessage() {}

func (x *KickPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickPlayer.ProtoReflect.Descriptor instead.
func (*KickPlayer) Descriptor() ([]byte, []int) {
	return file_proto_hub_proto_rawDescGZIP(), []int{9}
}

func (x *KickPlayer) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *KickPlayer) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ConfigUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"` // Agent should call FetchConfig to get the latest config.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigUpdate) Reset() {
	*x = ConfigUpdate{}
	mi := &file_proto_hub_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdate) ProtoMessage() {}

func (x *ConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdate.ProtoReflect.Descriptor instead.
func (*ConfigUpdate) Descriptor() ([]byte, []int) {
	return file_proto_hub_proto_rawDescGZIP(), []int{10}
}

func (x *ConfigUpdate) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Announcement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"` // "info" | "warning" | "maintenance"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Announcement) Reset() {
	*x = Announcement{}
	mi := &file_proto_hub_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Announcement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Announcement) ProtoMessage() {}

func (x *Announcement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Announcement.ProtoReflect.Descriptor instead.
func (*Announcement) Descriptor() ([]byte, []int) {
	return file_proto_hub_proto_rawDescGZIP(), []int{11}
}

func (x *Announcement) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Announcement) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

type ConfigRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AgentToken        string                 `protobuf:"bytes,1,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`
	CurrentConfigHash string                 `protobuf:"bytes,2,opt,name=current_config_hash,json=currentConfigHash,proto3" json:"current_config_hash,omitempty"` // SHA-256 of current config (for change detection)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConfigRequest) Reset() {
	*x = ConfigRequest{}
	mi := &file_proto_hub_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRequest) ProtoMessage() {}

func (x *ConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRequest.ProtoReflect.Descriptor instead.
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_hub_proto_rawDescGZIP(), []int{12}
}

func (x *ConfigRequest) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

func (x *ConfigRequest) GetCurrentConfigHash() string {
	if x != nil {
		return x.CurrentConfigHash
	}
	return ""
}

type AgentConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TenantId         string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TenantSlug       string                 `protobuf:"bytes,2,opt,name=tenant_slug,json=tenantSlug,proto3" json:"tenant_slug,omitempty"`
	PublicGateIp     string                 `protobuf:"bytes,3,opt,name=public_gate_ip,json=publicGateIp,proto3" json:"public_gate_ip,omitempty"`
	Servers          []*ServerLineConfig    `protobuf:"bytes,4,rep,name=servers,proto3" json:"servers,omitempty"`
	PatchManifestUrl string                 `protobuf:"bytes,5,opt,name=patch_manifest_url,json=patchManifestUrl,proto3" json:"patch_manifest_url,omitempty"`
	NewsUrl          string                 `protobuf:"bytes,6,opt,name=news_url,json=newsUrl,proto3" json:"news_url,omitempty"`
	Branding         *BrandingConfig        `protobuf:"bytes,7,opt,name=branding,proto3" json:"branding,omitempty"`
	ConfigHash       []byte                 `protobuf:"bytes,8,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AgentConfig) Reset() {
	*x = AgentConfig{}
	mi := &file_proto_hub_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfig) ProtoMessage() {}

func (x *AgentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfig.ProtoReflect.Descriptor instead.
func (*AgentConfig) Descriptor() ([]byte, []int) {
	return file_proto_hub_proto_rawDescGZIP(), []int{13}
}

func (x *AgentConfig) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AgentConfig) GetTenantSlug() string {
	if x != nil {
		return x.TenantSlug
	}
	return ""
}

func (x *AgentConfig) GetPublicGateIp() string {
	if x != nil {
		return x.PublicGateIp
	}
	return ""
}

func (x *AgentConfig) GetServers() []*ServerLineConfig {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *AgentConfig) GetPatchManifestUrl() string {
	if x != nil {
		return x.PatchManifestUrl
	}
	return ""
}

func (x *AgentConfig) GetNewsUrl() string {
	if x != nil {
		return x.NewsUrl
	}
	return ""
}

func (x *AgentConfig) GetBranding() *BrandingConfig {
	if x != nil {
		return x.Branding
	}
	return nil
}

func (x *AgentConfig) GetConfigHash() []byte {
	if x != nil {
		return x.ConfigHash
	}
	return nil
}

type ServerLineConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"` // "5.8" or "4.8"
	AuthPort      int32                  `protobuf:"varint,4,opt,name=auth_port,json=authPort,proto3" json:"auth_port,omitempty"`
	GamePort      int32                  `protobuf:"varint,5,opt,name=game_port,json=gamePort,proto3" json:"game_port,omitempty"`
	ChatPort      int32                  `protobuf:"varint,6,opt,name=chat_port,json=chatPort,proto3" json:"chat_port,omitempty"`
	GameArgs      string                 `protobuf:"bytes,7,opt,name=game_args,json=gameArgs,proto3" json:"game_args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerLineConfig) Reset() {
	*x = ServerLineConfig{}
	mi := &file_proto_hub_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerLineConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerLineConfig) ProtoMessage() {}

func (x *ServerLineConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerLineConfig.ProtoReflect.Descriptor instead.
func (*ServerLineConfig) Descriptor() ([]byte, []int) {
	return file_proto_hub_proto_rawDescGZIP(), []int{14}
}

func (x *ServerLineConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServerLineConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerLineConfig) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServerLineConfig) GetAuthPort() int32 {
	if x != nil {
		return x.AuthPort
	}
	return 0
}

func (x *ServerLineConfig) GetGamePort() int32 {
	if x != nil {
		return x.GamePort
	}
	return 0
}

func (x *ServerLineConfig) GetChatPort() int32 {
	if x != nil {
		return x.ChatPort
	}
	return 0
}

func (x *ServerLineConfig) GetGameArgs() string {
	if x != nil {
		return x.GameArgs
	}
	return ""
}

type BrandingConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerName    string                 `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	LogoUrl       string                 `protobuf:"bytes,2,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	BgUrl         string                 `protobuf:"bytes,3,opt,name=bg_url,json=bgUrl,proto3" json:"bg_url,omitempty"`
	AccentColor   string                 `protobuf:"bytes,4,opt,name=accent_color,json=accentColor,proto3" json:"accent_color,omitempty"`
	TextColor     string                 `protobuf:"bytes,5,opt,name=text_color,json=textColor,proto3" json:"text_color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrandingConfig) Reset() {
	*x = BrandingConfig{}
	mi := &file_proto_hub_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrandingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrandingConfig) ProtoMessage() {}

func (x *BrandingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrandingConfig.ProtoReflect.Descriptor instead.
func (*BrandingConfig) Descriptor() ([]byte, []int) {
	return file_proto_hub_proto_rawDescGZIP(), []int{15}
}

func (x *BrandingConfig) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *BrandingConfig) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *BrandingConfig) GetBgUrl() string {
	if x != nil {
		return x.BgUrl
	}
	return ""
}

func (x *BrandingConfig) GetAccentColor() string {
	if x != nil {
		return x.AccentColor
	}
	return ""
}

func (x *BrandingConfig) GetTextColor() string {
	if x != nil {
		return x.TextColor
	}
	return ""
}

type PushCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Command       *HubCommand            `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushCommandRequest) Reset() {
	*x = PushCommandRequest{}
	mi := &file_proto_hub_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushCommandRequest) ProtoMessage() {}

func (x *PushCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushCommandRequest.ProtoReflect.Descriptor instead.
func (*PushCommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_hub_proto_rawDescGZIP(), []int{16}
}

func (x *PushCommandRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PushCommandRequest) GetCommand() *HubCommand {
	if x != nil {
		return x.Command
	}
	return nil
}

type PushCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivered     bool                   `protobuf:"varint,1,opt,name=delivered,proto3" json:"delivered,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushCommandResponse) Reset() {
	*x = PushCommandResponse{}
	mi := &file_proto_hub_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushCommandResponse) ProtoMessage() {}

func (x *PushCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushCommandResponse.ProtoReflect.Descriptor instead.
func (*PushCommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_hub_proto_rawDescGZIP(), []int{17}
}

func (x *PushCommandResponse) GetDelivered() bool {
	if x != nil {
		return x.Delivered
	}
	return false
}

func (x *PushCommandResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_hub_proto protoreflect.FileDescriptor

const file_proto_hub_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/hub.proto\x12\x0fshiguang.hub.v1\"\xe6\x01\n" +
	"\vAgentReport\x12\x1f\n" +
	"\vagent_token\x18\x01 \x01(\tR\n" +
	"agentToken\x12:\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1a.shiguang.hub.v1.HeartbeatH\x00R\theartbeat\x129\n" +
	"\ametrics\x18\x03 \x01(\v2\x1d.shiguang.hub.v1.MetricsBatchH\x00R\ametrics\x124\n" +
	"\x05event\x18\x04 \x01(\v2\x1c.shiguang.hub.v1.PlayerEventH\x00R\x05eventB\t\n" +
	"\apayload\"\xe3\x01\n" +
	"\tHeartbeat\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1b\n" +
	"\tpublic_ip\x18\x02 \x01(\tR\bpublicIp\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x16\n" +
	"\x06uptime\x18\x05 \x01(\tR\x06uptime\x126\n" +
	"\x06routes\x18\x06 \x03(\v2\x1e.shiguang.hub.v1.RouteSnapshotR\x06routes\x12\x1b\n" +
	"\tban_count\x18\a \x01(\x05R\bbanCount\"s\n" +
	"\rRouteSnapshot\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06active\x18\x02 \x01(\x03R\x06active\x12\x1a\n" +
	"\baccepted\x18\x03 \x01(\x04R\baccepted\x12\x1a\n" +
	"\brejected\x18\x04 \x01(\x04R\brejected\"D\n" +
	"\fMetricsBatch\x124\n" +
	"\x06points\x18\x01 \x03(\v2\x1c.shiguang.hub.v1.MetricPointR\x06points\"r\n" +
	"\vMetricPoint\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\x12\x16\n" +
	"\x06server\x18\x03 \x01(\tR\x06server\x12!\n" +
	"\ftimestamp_ms\x18\x04 \x01(\x03R\vtimestampMs\"\x86\x01\n" +
	"\vPlayerEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\x12\x16\n" +
	"\x06server\x18\x03 \x01(\tR\x06server\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12!\n" +
	"\ftimestamp_ms\x18\x05 \x01(\x03R\vtimestampMs\"\xca\x02\n" +
	"\n" +
	"HubCommand\x12/\n" +
	"\x06ban_ip\x18\x01 \x01(\v2\x16.shiguang.hub.v1.BanIPH\x00R\x05banIp\x125\n" +
	"\bunban_ip\x18\x02 \x01(\v2\x18.shiguang.hub.v1.UnbanIPH\x00R\aunbanIp\x12>\n" +
	"\vkick_player\x18\x03 \x01(\v2\x1b.shiguang.hub.v1.KickPlayerH\x00R\n" +
	"kickPlayer\x12D\n" +
	"\rconfig_update\x18\x04 \x01(\v2\x1d.shiguang.hub.v1.ConfigUpdateH\x00R\fconfigUpdate\x12C\n" +
	"\fannouncement\x18\x05 \x01(\v2\x1d.shiguang.hub.v1.AnnouncementH\x00R\fannouncementB\t\n" +
	"\acommand\"P\n" +
	"\x05BanIP\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\"\x19\n" +
	"\aUnbanIP\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\">\n" +
	"\n" +
	"KickPlayer\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"&\n" +
	"\fConfigUpdate\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"D\n" +
	"\fAnnouncement\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\"`\n" +
	"\rConfigRequest\x12\x1f\n" +
	"\vagent_token\x18\x01 \x01(\tR\n" +
	"agentToken\x12.\n" +
	"\x13current_config_hash\x18\x02 \x01(\tR\x11currentConfigHash\"\xd5\x02\n" +
	"\vAgentConfig\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vtenant_slug\x18\x02 \x01(\tR\n" +
	"tenantSlug\x12$\n" +
	"\x0epublic_gate_ip\x18\x03 \x01(\tR\fpublicGateIp\x12;\n" +
	"\aservers\x18\x04 \x03(\v2!.shiguang.hub.v1.ServerLineConfigR\aservers\x12,\n" +
	"\x12patch_manifest_url\x18\x05 \x01(\tR\x10patchManifestUrl\x12\x19\n" +
	"\bnews_url\x18\x06 \x01(\tR\anewsUrl\x12;\n" +
	"\bbranding\x18\a \x01(\v2\x1f.shiguang.hub.v1.BrandingConfigR\bbranding\x12\x1f\n" +
	"\vconfig_hash\x18\b \x01(\fR\n" +
	"configHash\"\xc4\x01\n" +
	"\x10ServerLineConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1b\n" +
	"\tauth_port\x18\x04 \x01(\x05R\bauthPort\x12\x1b\n" +
	"\tgame_port\x18\x05 \x01(\x05R\bgamePort\x12\x1b\n" +
	"\tchat_port\x18\x06 \x01(\x05R\bchatPort\x12\x1b\n" +
	"\tgame_args\x18\a \x01(\tR\bgameArgs\"\xa5\x01\n" +
	"\x0eBrandingConfig\x12\x1f\n" +
	"\vserver_name\x18\x01 \x01(\tR\n" +
	"serverName\x12\x19\n" +
	"\blogo_url\x18\x02 \x01(\tR\alogoUrl\x12\x15\n" +
	"\x06bg_url\x18\x03 \x01(\tR\x05bgUrl\x12!\n" +
	"\faccent_color\x18\x04 \x01(\tR\vaccentColor\x12\x1d\n" +
	"\n" +
	"text_color\x18\x05 \x01(\tR\ttextColor\"h\n" +
	"\x12PushCommandRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x125\n" +
	"\acommand\x18\x02 \x01(\v2\x1b.shiguang.hub.v1.HubCommandR\acommand\"I\n" +
	"\x13PushCommandResponse\x12\x1c\n" +
	"\tdelivered\x18\x01 \x01(\bR\tdelivered\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\x80\x02\n" +
	"\bAgentHub\x12M\n" +
	"\fReportStream\x12\x1c.shiguang.hub.v1.AgentReport\x1a\x1b.shiguang.hub.v1.HubCommand(\x010\x01\x12K\n" +
	"\vFetchConfig\x12\x1e.shiguang.hub.v1.ConfigRequest\x1a\x1c.shiguang.hub.v1.AgentConfig\x12X\n" +
	"\vPushCommand\x12#.shiguang.hub.v1.PushCommandRequest\x1a$.shiguang.hub.v1.PushCommandResponseB\"Z github.com/shiguang/shared/hubpbb\x06proto3"

var (
	file_proto_hub_proto_rawDescOnce sync.Once
	file_proto_hub_proto_rawDescData []byte
)

func file_proto_hub_proto_rawDescGZIP() []byte {
	file_proto_hub_proto_rawDescOnce.Do(func() {
		file_proto_hub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hub_proto_rawDesc), len(file_proto_hub_proto_rawDesc)))
	})
	return file_proto_hub_proto_rawDescData
}

var file_proto_hub_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_hub_proto_goTypes = []any{
	(*AgentReport)(nil),         // 0: shiguang.hub.v1.AgentReport
	(*Heartbeat)(nil),           // 1: shiguang.hub.v1.Heartbeat
	(*RouteSnapshot)(nil),       // 2: shiguang.hub.v1.RouteSnapshot
	(*MetricsBatch)(nil),        // 3: shiguang.hub.v1.MetricsBatch
	(*MetricPoint)(nil),         // 4: shiguang.hub.v1.MetricPoint
	(*PlayerEvent)(nil),         // 5: shiguang.hub.v1.PlayerEvent
	(*HubCommand)(nil),          // 6: shiguang.hub.v1.HubCommand
	(*BanIP)(nil),               // 7: shiguang.hub.v1.BanIP
	(*UnbanIP)(nil),             // 8: shiguang.hub.v1.UnbanIP
	(*KickPlayer)(nil),          // 9: shiguang.hub.v1.KickPlayer
	(*ConfigUpdate)(nil),        // 10: shiguang.hub.v1.ConfigUpdate
	(*Announcement)(nil),        // 11: shiguang.hub.v1.Announcement
	(*ConfigRequest)(nil),       // 12: shiguang.hub.v1.ConfigRequest
	(*AgentConfig)(nil),         // 13: shiguang.hub.v1.AgentConfig
	(*ServerLineConfig)(nil),    // 14: shiguang.hub.v1.ServerLineConfig
	(*BrandingConfig)(nil),      // 15: shiguang.hub.v1.BrandingConfig
	(*PushCommandRequest)(nil),  // 16: shiguang.hub.v1.PushCommandRequest
	(*PushCommandResponse)(nil), // 17: shiguang.hub.v1.PushCommandResponse
}
var file_proto_hub_proto_depIdxs = []int32{
	1,  // 0: shiguang.hub.v1.AgentReport.heartbeat:type_name -> shiguang.hub.v1.Heartbeat
	3,  // 1: shiguang.hub.v1.AgentReport.metrics:type_name -> shiguang.hub.v1.MetricsBatch
	5,  // 2: shiguang.hub.v1.AgentReport.event:type_name -> shiguang.hub.v1.PlayerEvent
	2,  // 3: shiguang.hub.v1.Heartbeat.routes:type_name -> shiguang.hub.v1.RouteSnapshot
	4,  // 4: shiguang.hub.v1.MetricsBatch.points:type_name -> shiguang.hub.v1.MetricPoint
	7,  // 5: shiguang.hub.v1.HubCommand.ban_ip:type_name -> shiguang.hub.v1.BanIP
	8,  // 6: shiguang.hub.v1.HubCommand.unban_ip:type_name -> shiguang.hub.v1.UnbanIP
	9,  // 7: shiguang.hub.v1.HubCommand.kick_player:type_name -> shiguang.hub.v1.KickPlayer
	10, // 8: shiguang.hub.v1.HubCommand.config_update:type_name -> shiguang.hub.v1.ConfigUpdate
	11, // 9: shiguang.hub.v1.HubCommand.announcement:type_name -> shiguang.hub.v1.Announcement
	14, // 10: shiguang.hub.v1.AgentConfig.servers:type_name -> shiguang.hub.v1.ServerLineConfig
	15, // 11: shiguang.hub.v1.AgentConfig.branding:type_name -> shiguang.hub.v1.BrandingConfig
	6,  // 12: shiguang.hub.v1.PushCommandRequest.command:type_name -> shiguang.hub.v1.HubCommand
	0,  // 13: shiguang.hub.v1.AgentHub.ReportStream:input_type -> shiguang.hub.v1.AgentReport
	12, // 14: shiguang.hub.v1.AgentHub.FetchConfig:input_type -> shiguang.hub.v1.ConfigRequest
	16, // 15: shiguang.hub.v1.AgentHub.PushCommand:input_type -> shiguang.hub.v1.PushCommandRequest
	6,  // 16: shiguang.hub.v1.AgentHub.ReportStream:output_type -> shiguang.hub.v1.HubCommand
	13, // 17: shiguang.hub.v1.AgentHub.FetchConfig:output_type -> shiguang.hub.v1.AgentConfig
	17, // 18: shiguang.hub.v1.AgentHub.PushCommand:output_type -> shiguang.hub.v1.PushCommandResponse
	16, // [16:19] is the sub-list for method output_type
	13, // [13:16] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_hub_proto_init() }
func file_proto_hub_proto_init() {
	if File_proto_hub_proto != nil {
		return
	}
	file_proto_hub_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentReport_Heartbeat)(nil),
		(*AgentReport_Metrics)(nil),
		(*AgentReport_Event)(nil),
	}
	file_proto_hub_proto_msgTypes[6].OneofWrappers = []any{
		(*HubCommand_BanIp)(nil),
		(*HubCommand_UnbanIp)(nil),
		(*HubCommand_KickPlayer)(nil),
		(*HubCommand_ConfigUpdate)(nil),
		(*HubCommand_Announcement)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hub_proto_rawDesc), len(file_proto_hub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hub_proto_goTypes,
		DependencyIndexes: file_proto_hub_proto_depIdxs,
		MessageInfos:      file_proto_hub_proto_msgTypes,
	}.Build()
	File_proto_hub_proto = out.File
	file_proto_hub_proto_goTypes = nil
	file_proto_hub_proto_depIdxs = nil
}
