// Hub-Spoke gRPC protocol for ShiguangCloud.
//
// The Gate Agent (spoke) connects to Hub (cloud) via a long-lived bidirectional
// gRPC stream. This stream carries:
//   Agent → Hub: heartbeat, metrics, events (player login/logout)
//   Hub → Agent: ban/unban, kick, config hot-push, announcements
//
// Game traffic (TCP packets) NEVER flows through this channel — only the
// control plane does. This is the foundational design principle.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/hub.proto

package hubpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentHub_ReportStream_FullMethodName = "/shiguang.hub.v1.AgentHub/ReportStream"
	AgentHub_FetchConfig_FullMethodName  = "/shiguang.hub.v1.AgentHub/FetchConfig"
	AgentHub_PushCommand_FullMethodName  = "/shiguang.hub.v1.AgentHub/PushCommand"
)

// AgentHubClient is the client API for AgentHub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentHubClient interface {
	// Long-lived bidirectional stream.
	// Agent sends reports; Hub sends commands on the same stream.
	ReportStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentReport, HubCommand], error)
	// One-shot config pull on agent startup (before opening ReportStream).
	FetchConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*AgentConfig, error)
	// Called by Hub's REST layer when an operator hits "ban IP" in the dashboard.
	// This is an internal RPC, not exposed to agents.
	PushCommand(ctx context.Context, in *PushCommandRequest, opts ...grpc.CallOption) (*PushCommandResponse, error)
}

type agentHubClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentHubClient(cc grpc.ClientConnInterface) AgentHubClient {
	return &agentHubClient{cc}
}

func (c *agentHubClient) ReportStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentReport, HubCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentHub_ServiceDesc.Streams[0], AgentHub_ReportStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentReport, HubCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentHub_ReportStreamClient = grpc.BidiStreamingClient[AgentReport, HubCommand]

func (c *agentHubClient) FetchConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*AgentConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentConfig)
	err := c.cc.Invoke(ctx, AgentHub_FetchConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentHubClient) PushCommand(ctx context.Context, in *PushCommandRequest, opts ...grpc.CallOption) (*PushCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushCommandResponse)
	err := c.cc.Invoke(ctx, AgentHub_PushCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentHubServer is the server API for AgentHub service.
// All implementations must embed UnimplementedAgentHubServer
// for forward compatibility.
type AgentHubServer interface {
	// Long-lived bidirectional stream.
	// Agent sends reports; Hub sends commands on the same stream.
	ReportStream(grpc.BidiStreamingServer[AgentReport, HubCommand]) error
	// One-shot config pull on agent startup (before opening ReportStream).
	FetchConfig(context.Context, *ConfigRequest) (*AgentConfig, error)
	// Called by Hub's REST layer when an operator hits "ban IP" in the dashboard.
	// This is an internal RPC, not exposed to agents.
	PushCommand(context.Context, *PushCommandRequest) (*PushCommandResponse, error)
	mustEmbedUnimplementedAgentHubServer()
}

// UnimplementedAgentHubServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentHubServer struct{}

func (UnimplementedAgentHubServer) ReportStream(grpc.BidiStreamingServer[AgentReport, HubCommand]) error {
	return status.Error(codes.Unimplemented, "method ReportStream not implemented")
}
func (UnimplementedAgentHubServer) FetchConfig(context.Context, *ConfigRequest) (*AgentConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchConfig not implemented")
}
func (UnimplementedAgentHubServer) PushCommand(context.Context, *PushCommandRequest) (*PushCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PushCommand not implemented")
}
func (UnimplementedAgentHubServer) mustEmbedUnimplementedAgentHubServer() {}
func (UnimplementedAgentHubServer) testEmbeddedByValue()                  {}

// UnsafeAgentHubServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentHubServer will
// result in compilation errors.
type UnsafeAgentHubServer interface {
	mustEmbedUnimplementedAgentHubServer()
}

func RegisterAgentHubServer(s grpc.ServiceRegistrar, srv AgentHubServer) {
	// If the following call panics, it indicates UnimplementedAgentHubServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentHub_ServiceDesc, srv)
}

func _AgentHub_ReportStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentHubServer).ReportStream(&grpc.GenericServerStream[AgentReport, HubCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentHub_ReportStreamServer = grpc.BidiStreamingServer[AgentReport, HubCommand]

func _AgentHub_FetchConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentHubServer).FetchConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentHub_FetchConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentHubServer).FetchConfig(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentHub_PushCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentHubServer).PushCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentHub_PushCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentHubServer).PushCommand(ctx, req.(*PushCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentHub_ServiceDesc is the grpc.ServiceDesc for AgentHub service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentHub_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shiguang.hub.v1.AgentHub",
	HandlerType: (*AgentHubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchConfig",
			Handler:    _AgentHub_FetchConfig_Handler,
		},
		{
			MethodName: "PushCommand",
			Handler:    _AgentHub_PushCommand_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportStream",
			Handler:       _AgentHub_ReportStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/hub.proto",
}
